accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.views.generic import ListView,DetailView
from django.urls import path
from .models import post

urlpatterns =[
    path("",
         ListView.as_view(
             queryset = 
             post.objects.all().order_by("-date")[:25],
             template_name = "blog.html."
         )
         ),
    path("<int:pk>/",
         DetailView.as_view(
             model = post,
             template_name = "post.html" 
             
             )
        ),

         
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from pages import views


urlpatterns = [
    path('',views.homeview, name="home"),
    path('admin/', admin.site.urls),
    path("webapp/", include("webapp.urls")),
    path("webapp2/", include("webapp2.urls")),
    path("blog/", include("blog.urls")),
    path("polls/", include("polls.urls")),
    path("user_auth/", include("django.contrib.auth.urls")),
    path("user_auth/", include("user_auth.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls"))
    
  
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path, include
from . import views

app_name = "user_auth"
app_name = "polls"
urlpatterns = [
    
    path("", views.index, name ="index"),
    path("<int:question_id>", views.detail, name = "detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote")

]

user_auth/urls.py
from django.urls import path
from . import views


app_name = "user_auth"

urlpatterns = [
    path('', views.user_login, name="login"),
    path('authenticate_user/', views.authenticate_user,
name='authenticate_user'),
    path('show_user/', views.show_user,
name='show_user')
]

webapp/urls.py
from django.urls import path, include
from.import views


urlpatterns = [path("",views.index),]

webapp2/urls.py
from django.urls import path, include
from.import views


urlpatterns = [path("",views.index1),]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

class post(models.Model):
    title = models.CharField(max_length = 140)
    body = models.CharField(max_length = 140)
    singnature = models.CharField(max_length = 140, default="Jesse")
    date = models.CharField(max_length = 140)

    def __str__(self):
        return self.title

# Create your models here.

mysite/mysite/models.py
from django.db import models

# Create your models here.

mysite/mysite/mysite/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
# Create your models here.

user_auth/models.py
from django.db import models

# Create your models here.

webapp/models.py
# Create your models here.

webapp2/models.py
# Create your models here.

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic



class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("home")
    template_name = "registration/signup.html"

blog/views.py
from django.shortcuts import render

# Create your views here.

mysite/mysite/mysite/views.py
from django.shortcuts import render

# Create your views here.

mysite/mysite/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

def homeview(*args,**kwargs):
    return HttpResponse("<center><ul><h1>Home page</h1></ul></center>\n <h1>To register pls enter /accounts/signup</h1>\n<h1>To login pls enter /user_auth</h1>\n <h1>To access polls pls enter /polls</h1>\n <h1>To access webapp pls enter /webapp</h1>\n <h1>To access webapp2 pls enter /webapp2</h1>\n <h1>To access blog pls enter /blog</h1>")
# Create your views here.

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice
from django.contrib.auth.decorators import login_required




@login_required(login_url="/user_auth/") 
def index(request):
    #return HttpResponse("Hello world. You're at the polls index.")
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/poll.html", context)


def detail(request, question_id):
     question = get_object_or_404(Question, pk=question_id)
     return render(request, "polls/detail.html", {"question": question})


@login_required(login_url="/accounts/login/")   
def vote(request, question_id):
   question =get_object_or_404(Question, pk=question_id)
   try:
       selected_choice = question.choice_set.get(
           pk = request.POST['choice']
       )
   except (KeyError, Choice.DoesNotExist):
       
       return render(request, 'polls/details.html',{
           'question': question,
           'error message': "you didn't select a choice."
       })
   else:
       selected_choice.votes +=1
       selected_choice.save()



       return HttpResponseRedirect(
           reverse('polls:results', args=(question_id,))
       )
# Create your views here
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html',{'question':question})

user_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

def show_user(request):
    print(request.user.username)
    return render(request, 'authentication/user.html',{
        "username": request.user.username,
        "password": request.user.password
    })

def user_login(request):
    return render (request, 'authentication/login.html')

def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse("user_auth:login")

        )
    else:
        login(request,user)
        return HttpResponseRedirect(
            reverse('user_auth:show_user')
        )


# Create your views here.

webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
@login_required(login_url="/user_auth/") 
def index(request):
    return render(request,"index.html")





# Create your views here.

webapp2/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
@login_required(login_url="/user_auth/") 
def index1(request):
    return render(request,"index1.html")





# Create your views here.

polls/templates/polls/detail.html
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-12"><h1>{{question.question_text}}</h1>
        </div>
    </div>
</div>
{% if error_message %}
<p><strong>{{error_message}}</strong></p>
{% endif %}

<form action ="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}

    {% for choice in question.choice_set.all %}
    <div class="container">
        <div class="row">
            <div class="col-sm-4"><input type="radio" name="choice" id="choice {{ forloop.counter }}" value="{{ choice.id }}" />
                <div class="col-sm-4"><label for="choice {{ forloop.counter }}">
        {{ choice.choice_text }}
        </div>
    </div>
</div>
</div>
    </label>
    <br />
    {% endfor %}

    <input type="submit" value="Vote" />

</form>

polls/templates/polls/poll.html
<!DOCTYPE html>
{% load static %}
{% if latest_question_list %}
<h1>This will help me gather data for my organic food website!</h1>
<ul>
    {% for question in latest_question_list %}
    <li><div class="container">
        <div class="row">
            <div class="col-md-6"><a href = "{% url 'polls:detail' question.id %}">{{ question.question_text }}

        </a>
        </div>
        </div>
    </div>
    </li>
    {% endfor %}
    
</ul>

{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes }}
        vote{{choice.votes|pluralize}}
    </li>
    {% endfor %}

</ul>
<a href="{% url 'polls:detail' question.id %}">
    Vote again?
</a>

user_auth/templates/authentication/login.html
<h1>Login user</h1>
<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}
    <label>Username</label>
    <input type="text" name="username" placeholder="user" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>

    <input type="submit" value="login" />
    

</form>

user_auth/templates/authentication/user.html
<h1> Welcome,{{username}} </h1>
<p>Your password is {{password}}</p>

webapp/templates/index.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
  <title>Online food store</title>


  <link rel="stylesheet" href="stylesheet.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  <style>
    label{color: aliceblue;}
      h1{color: white;}
      body {
    background-image: url("{% static 'images/blackwallpaper.jpg' %}");  
    /* #background-repeat: no-repeat; */
            }
      p{color: red;}
    /* #holder {
        max-width: 200px;
        max-height: 200px;
        overflow: hidden;
      
      }
      
      #holder img {
        width: 100%;
         -webkit-transition: all 0.8s ease;
        -moz-transition: all 0.8s ease;
        transition: all 0.8s ease;
      }
      
      #holder img:hover {
        transform: scale(2,2);
      } */
      .item-image{transition: transform 0.5s ease; width: 80px;height: 80px;}
      .item-image:hover{transform: scale(1.1);}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}" >
</head>

<body>
  <center><h1><u>JESSE'S ORGANIC FOODS</u></h1></center>    
  <div class="row">
      
        <div class="col-md-3">
            <h1>apple</h1>
            <p>R5 per apple</p>
            <img class="item-image"src="{% static 'images/apples.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>
           

        </div> 
        
        <div class="col-md-3">
          <h1>banana</h1>
          <p>R4 per banana</p>
          <img class="item-image" src="{% static 'images/bannana.jfif' %}">
          <div> <button type="button" class="btn btn-danger">BUY</button></div>
      
        </div>

      
        <div class="col-md-3">
            <h1>Oranges</h1>
            <p>R6 per orange</p>
            <img class="item-image" src="{% static 'images/oranges.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>


        </div>

        <div class="col-md-3">
          <h1>pears</h1>
          <p>R7 per pear</p>
          <img class="item-image" src="{% static 'images/pears.jfif' %}">
          <div> <button type="button" class="btn btn-danger">BUY</button></div>


      </div>

        <div class="row">
      
          <div class="col-md-3">
              <h1>Fillet steak</h1>
              <p>R200 per kilo</p>
              <img class="item-image"src="{% static 'images/fillet.jfif' %}">
              <div> <button type="button" class="btn btn-danger">BUY</button></div>
              
             
  
          </div> 
          
          <div class="col-md-3">
            <h1>Chicken</h1>
            <p>R50 per kilo</p>
            <img class="item-image" src="{% static 'images/chicken.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>
        
          </div>
  
        
          <div class="col-md-3">
              <h1>milk</h1>
              <p>R30 per litre</p>
              <img class="item-image" src="{% static 'images/milk.jfif' %}">
              <div> <button type="button" class="btn btn-danger">BUY</button></div>
  
  
          </div>

          <div class="col-md-3">
            <h1>radishes</h1>
            <p>R1 per radish</p>
            <img class="item-image" src="{% static 'images/radish.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>


        </div>
     
  </div>


  <div class="row">
      
    <div class="col-md-3">
        <h1>soda</h1>
        <p>R15 per soda</p>
        <img class="item-image"src="{% static 'images/soda.jfif' %}">
        <div> <button type="button" class="btn btn-danger">BUY</button></div>
        
       

    </div> 
    
    <div class="col-md-3">
      <h1>protein</h1>
      <p>R700 per 4kg</p>
      <img class="item-image" src="{% static 'images/protein.jfif' %}">
      <div> <button type="button" class="btn btn-danger">BUY</button></div>
  
    </div>

  
    <div class="col-md-4">
        <h1>more coming soon......</h1>
        


    </div>
  </div>

  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="Name">Name</label>
         <div><input type="text" class="form-control"></div>
        </div>
        </form>
      </div>
      <div class="col-md-6">
        <img src="{% static 'images/logo.jpg' %}" img width="75px" img height="80px">
      </div>
    </div>
  </footer>
  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="Surname">Surname</label>
         <div><input type="text" class="form-control"></div>
        </div>
        </form>
      </div>
    </div>
  </footer>
  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="Email">Email</label>
         <div><input type="text" class="form-control"></div>
        </div>
        </form>
      </div>
      
    </div>
  </footer>
  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="phone">phone</label>
         <div><input type="text" class="form-control"></div>
         
         
        
          
           
          </div>
        </form>
      </div>
      
    </div>
    
  </footer>
</body>

webapp/templates/index1.html
{%load static%}
<html>
<head>
<body style = "background-color:#4287f5;">
<title>CV</title>
<style>
	h1
	{color:#361869;}
	h1{font-family: sans-serif;}
	p{font-size: larger;}
	p{font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;}
</style>
<h1><u>Bio</u></h1>
<h1><i>My name is Jesse Lustig, I am an aspiring software engineer with a passion for problem solving, creating and technology, I love helping people and want to make the world a better place.</i></h1>

<h1>Name:Jesse</h1>

<h1>Surname:Lustig</h1>

<h1>Phone:0670087489</h1>

<h1>Email:jesselustig46@gmail.com</h1>

<h1>Education:King David Victory Park Highschool.</h1>

<h1>Education:Hyperiondev software engineering bootcamp. </h1>

<h1>Projects include:Data bases,Calculators and games.</h1>

<h1>skills:Python,sqlite and html</h1>


<center><img src="{% static 'images/me.jfif' %}" /></center>
<br>
<br>
<center><u><h1>Linkedin_website</h1></u></center>
<center><a href="https://za.linkedin.com/">Linkedin.com</a></center>

<center><u><h1>github website</h1></u></center>
<center><a href="https://github.com/">github.com</a></center>
<br>
<center><img src="{% static 'images/python.jfif' %}" width="100" height="100" /><img src="{% static 'images/css.png' %}" width="100" height="100"/><img src="{% static 'images/sqlite.jfif' %}" width="100" height="100"/><img src="{% static 'images/html.png' %}" width="100" height="100"/></center>

webapp2/templates/index.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
  <title>Online food store</title>


  <link rel="stylesheet" href="stylesheet.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  <style>
    label{color: aliceblue;}
      h1{color: white;}
      body {
    background-image: url("{% static 'images/blackwallpaper.jpg' %}");  
    /* #background-repeat: no-repeat; */
            }
      p{color: red;}
    /* #holder {
        max-width: 200px;
        max-height: 200px;
        overflow: hidden;
      
      }
      
      #holder img {
        width: 100%;
         -webkit-transition: all 0.8s ease;
        -moz-transition: all 0.8s ease;
        transition: all 0.8s ease;
      }
      
      #holder img:hover {
        transform: scale(2,2);
      } */
      .item-image{transition: transform 0.5s ease; width: 80px;height: 80px;}
      .item-image:hover{transform: scale(1.1);}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}" >
</head>

<body>
  <center><h1><u>JESSE'S ORGANIC FOODS</u></h1></center>    
  <div class="row">
      
        <div class="col-md-3">
            <h1>apple</h1>
            <p>R5 per apple</p>
            <img class="item-image"src="{% static 'images/apples.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>
           

        </div> 
        
        <div class="col-md-3">
          <h1>banana</h1>
          <p>R4 per banana</p>
          <img class="item-image" src="{% static 'images/bannana.jfif' %}">
          <div> <button type="button" class="btn btn-danger">BUY</button></div>
      
        </div>

      
        <div class="col-md-3">
            <h1>Oranges</h1>
            <p>R6 per orange</p>
            <img class="item-image" src="{% static 'images/oranges.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>


        </div>

        <div class="col-md-3">
          <h1>pears</h1>
          <p>R7 per pear</p>
          <img class="item-image" src="{% static 'images/pears.jfif' %}">
          <div> <button type="button" class="btn btn-danger">BUY</button></div>


      </div>

        <div class="row">
      
          <div class="col-md-3">
              <h1>Fillet steak</h1>
              <p>R200 per kilo</p>
              <img class="item-image"src="{% static 'images/fillet.jfif' %}">
              <div> <button type="button" class="btn btn-danger">BUY</button></div>
              
             
  
          </div> 
          
          <div class="col-md-3">
            <h1>Chicken</h1>
            <p>R50 per kilo</p>
            <img class="item-image" src="{% static 'images/chicken.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>
        
          </div>
  
        
          <div class="col-md-3">
              <h1>milk</h1>
              <p>R30 per litre</p>
              <img class="item-image" src="{% static 'images/milk.jfif' %}">
              <div> <button type="button" class="btn btn-danger">BUY</button></div>
  
  
          </div>

          <div class="col-md-3">
            <h1>radishes</h1>
            <p>R1 per radish</p>
            <img class="item-image" src="{% static 'images/radish.jfif' %}">
            <div> <button type="button" class="btn btn-danger">BUY</button></div>


        </div>
     
  </div>


  <div class="row">
      
    <div class="col-md-3">
        <h1>soda</h1>
        <p>R15 per soda</p>
        <img class="item-image"src="{% static 'images/soda.jfif' %}">
        <div> <button type="button" class="btn btn-danger">BUY</button></div>
        
       

    </div> 
    
    <div class="col-md-3">
      <h1>protein</h1>
      <p>R700 per 4kg</p>
      <img class="item-image" src="{% static 'images/protein.jfif' %}">
      <div> <button type="button" class="btn btn-danger">BUY</button></div>
  
    </div>

  
    <div class="col-md-4">
        <h1>more coming soon......</h1>
        


    </div>
  </div>

  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="Name">Name</label>
         <div><input type="text" class="form-control"></div>
        </div>
        </form>
      </div>
      <div class="col-md-6">
        <img src="{% static 'images/logo.jpg' %}" img width="75px" img height="80px">
      </div>
    </div>
  </footer>
  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="Surname">Surname</label>
         <div><input type="text" class="form-control"></div>
        </div>
        </form>
      </div>
    </div>
  </footer>
  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="Email">Email</label>
         <div><input type="text" class="form-control"></div>
        </div>
        </form>
      </div>
      
    </div>
  </footer>
  <footer>
    <div class="row">
      <div class="col-md-4">
        <form>
         <div class="form-group row">
          <label for="phone">phone</label>
         <div><input type="text" class="form-control"></div>
         
         
        
          
           
          </div>
        </form>
      </div>
      
    </div>
    
  </footer>
</body>

webapp2/templates/index1.html
{%load static%}
<html>
<head>
<body style = "background-color:#4287f5;">
<title>CV</title>
<style>
	h1
	{color:#361869;}
	h1{font-family: sans-serif;}
	p{font-size: larger;}
	p{font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;}
</style>
<h1><u>Bio</u></h1>
<h1><i>My name is Jesse Lustig, I am an aspiring software engineer with a passion for problem solving, creating and technology, I love helping people and want to make the world a better place.</i></h1>

<h1>Name:Jesse</h1>

<h1>Surname:Lustig</h1>

<h1>Phone:0670087489</h1>

<h1>Email:jesselustig46@gmail.com</h1>

<h1>Education:King David Victory Park Highschool.</h1>

<h1>Education:Hyperiondev software engineering bootcamp. </h1>

<h1>Projects include:Data bases,Calculators and games.</h1>

<h1>skills:Python,sqlite and html</h1>


<center><img src="{% static 'images/me.jfif' %}" /></center>
<br>
<br>
<center><u><h1>Linkedin_website</h1></u></center>
<center><a href="https://za.linkedin.com/">Linkedin.com</a></center>

<center><u><h1>github website</h1></u></center>
<center><a href="https://github.com/">github.com</a></center>
<br>
<center><img src="{% static 'images/python.jfif' %}" width="100" height="100" /><img src="{% static 'images/css.png' %}" width="100" height="100"/><img src="{% static 'images/sqlite.jfif' %}" width="100" height="100"/><img src="{% static 'images/html.png' %}" width="100" height="100"/></center>